org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# 🔥 禁用 Gradle 缓存（磁盘空间不足）
org.gradle.caching=false
# 启用并行编译
org.gradle.parallel=true
# 按需配置
org.gradle.configureondemand=true

# 🔥 迁移Gradle缓存到D盘
org.gradle.user.home=D\:/.gradle
